[project]
  name = "amazon-titan-example"
  version = "0.1.0"
  description = "Add your description here"
  readme = "README.md"
  requires-python = ">=3.13"
  dependencies = [
    "boto3>=1.35.37",
    "numpy>=2.1.2",
]

[tool.uv]
  dev-dependencies = ["boto3-stubs[bedrock-runtime]>=1.35.37"]
